// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.ProductToProductTagLinks.Models
{

    public partial class ProductTagToProductLinkModel
    {

        public Guid Id { get; set; }


        public Guid ProductId { get; set; }


        public Guid ProductTagId { get; set; }


        public string ProductTagName { get; set; }


        public string ProductTagSeoLink { get; set; }
    }
}