// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.GiftCertificates.Models;
using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.GiftCertificates
{
    /// <summary>
    /// Прокси для GetCustomerGiftCertificatePdfCommand
    /// </summary>
    public partial class GetCustomerGiftCertificatePdfCommandProxy : ProxyBase<Guid, CertificatePdfModel>
    {
        public GetCustomerGiftCertificatePdfCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}