// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.GiftCertificates.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.GiftCertificates
{
    /// <summary>
    /// Прокси для GetCustomerGiftCertificatesQuery
    /// </summary>
    public partial class GetCustomerGiftCertificatesQueryProxy : ProxyBase<CertificateInputModel, IEnumerable<CertificateModel>>
    {
        public GetCustomerGiftCertificatesQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}