// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.GiftCertificates
{
    /// <summary>
    /// Прокси для GetCustomerGiftCertificateBarCodeCommand
    /// </summary>
    public partial class GetCustomerGiftCertificateBarCodeQueryProxy : ProxyBase<Guid, string>
    {
        public GetCustomerGiftCertificateBarCodeQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}