// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.CustomerOrders.Models;

namespace NverCard.Public.Client.ServiceProxies.Commands.CustomerOrders
{
    /// <summary>
    /// Прокси для CreateCustomerOrderCommand
    /// </summary>
    public partial class CreateCustomerOrderCommandProxy : ProxyBaseNoResult<CreateCustomerOrderModel>
    {
        public CreateCustomerOrderCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}