// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.CustomerOrders.Models;

namespace NverCard.Public.Client.ServiceProxies.Commands.CustomerOrders
{
    /// <summary>
    /// Прокси для UpdateCustomerOrderCommand
    /// </summary>
    public partial class UpdateCustomerOrderCommandProxy : ProxyBaseNoResult<UpdateCustomerOrderModel>
    {
        public UpdateCustomerOrderCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}