// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.ProductCategories.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.ProductCategories
{
    /// <summary>
    /// Прокси для GetAvailableProductCategoriesQuery
    /// </summary>
    public partial class GetAvailableProductCategoriesQueryProxy : ProxyBaseNoInput<IEnumerable<ProductCategoryModel>>
    {
        public GetAvailableProductCategoriesQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}