// AUTOGENERATED!!!!!!!!!!!!

namespace NverCard.Public.Client.ServiceProxies.Queries.ProductCategories
{
    /// <summary>
    /// Прокси для GetProductCategoryNameBySeoLinkQuery
    /// </summary>
    public partial class GetProductCategoryNameBySeoLinkQueryProxy : ProxyBase<string, string>
    {
        public GetProductCategoryNameBySeoLinkQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}