// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.ProductCategories.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.ProductCategories
{
    /// <summary>
    /// Прокси для GetProductCategoriesQuery
    /// </summary>
    public partial class GetProductCategoriesQueryProxy : ProxyBaseNoInput<IEnumerable<ProductCategoryModel>>
    {
        public GetProductCategoriesQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}