// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.ProductCategories.Models;
using System;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.ProductCategories
{
    /// <summary>
    /// Прокси для GetProductCategoriesForParentQuery
    /// </summary>
    public partial class GetProductCategoriesForParentQueryProxy : ProxyBase<Guid, IEnumerable<ProductCategoryModel>>
    {
        public GetProductCategoriesForParentQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}