// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.ProductCategories.Models;

namespace NverCard.Public.Client.ServiceProxies.Queries.ProductCategories
{
    /// <summary>
    /// Прокси для GetProductCategoriesBySeoLinkQuery
    /// </summary>
    public partial class GetProductCategoriesBySeoLinkQueryProxy : ProxyBase<string, ProductCategoryModel>
    {
        public GetProductCategoriesBySeoLinkQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}