// AUTOGENERATED!!!!!!!!!!!!

using System;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts.Models
{

    public partial class CreateShoppingCartModel
    {
        /// <summary>
        /// Creation date time
        /// </summary>
        public DateTime? CreationDateTime { get; set; }

        /// <summary>
        /// Customer
        /// </summary>
        public Guid CustomerId { get; set; }

        /// <summary>
        /// Shopping cart items
        /// </summary>
        public ICollection<CreateShoppingCartItemModel> CartItems { get; set; }
    }
}