// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts.Models
{

    public partial class CreateShoppingCartItemModel
    {

        public int Quantity { get; set; }


        public Guid OfferId { get; set; }
    }
}