// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts.Models
{

    public partial class CreateShoppingCartItemResultModel
    {

        public Guid CustomerId { get; set; }
    }
}