// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts.Models
{

    public partial class ShoppingCartModel
    {

        public Guid Id { get; set; }


        public Guid CustomerId { get; set; }
    }
}