// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts.Models
{

    public partial class UpdateShoppingCartItemModel
    {
        public Guid ShoppingCartId { get; set; }

        public Guid OfferId { get; set; }


        public int Quantity { get; set; }
    }
}