// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.ShoppingCarts.Models;

namespace NverCard.Public.Client.ServiceProxies.Queries.ShoppingCarts
{
    /// <summary>
    /// Прокси для GetCustomerShoppingCartQuery
    /// </summary>
    public partial class GetCustomerShoppingCartQueryProxy : ProxyBaseNoInput<ShoppingCartModel>
    {
        public GetCustomerShoppingCartQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}