// AUTOGENERATED!!!!!!!!!!!!

namespace NverCard.Public.Client.ServiceProxies.Queries.ShoppingCarts
{
    /// <summary>
    /// Прокси для GetCustomerShoppingCartItemsCountQuery
    /// </summary>
    public partial class GetCustomerShoppingCartItemsCountQueryProxy : ProxyBaseNoInput<int>
    {
        public GetCustomerShoppingCartItemsCountQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}