// AUTOGENERATED!!!!!!!!!!!!

namespace NverCard.Public.Client.ServiceProxies.Queries.ShoppingCarts
{
    /// <summary>
    /// Прокси для GetShoppingCartItemsAmountQuery
    /// </summary>
    public partial class GetShoppingCartItemsAmountQueryProxy : ProxyBaseNoInput<int>
    {
        public GetShoppingCartItemsAmountQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}