// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.CustomerOrders.Models
{

    public partial class CreateCustomerOrderItemModel
    {
        /// <summary>
        /// Количество
        /// </summary>
        public int Quantity { get; set; }

        /// <summary>
        /// Offer ID
        /// </summary>
        public Guid OfferId { get; set; }
    }
}