// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Dictionaries;
using System;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Commands.CustomerOrders.Models
{

    public partial class CreateCustomerOrderModel
    {
        /// <summary>
        /// Дата и время поступления заявки заказа
        /// </summary>
        public DateTime OrderRequestDateTime { get; set; }

        /// <summary>
        /// Дата и время сборки 
        /// </summary>
        public DateTime? AssemblyDateTime { get; set; }

        /// <summary>
        /// Дата и время отправки 
        /// </summary>
        public DateTime? SendingDateTime { get; set; }

        /// <summary>
        /// Номер заказа
        /// </summary>
        public string Number { get; set; }

        /// <summary>
        /// Дополнительная информация
        /// </summary>
        public string AdditionalInformation { get; set; }

        /// <summary>
        /// Email
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// Номер телефона
        /// </summary>
        public string PhoneNumber { get; set; }

        /// <summary>
        /// Delivery address
        /// </summary>
        public string FullDeliveryAddress { get; set; }

        /// <summary>
        /// Deliverable
        /// </summary>
        public bool Deliverable { get; set; }

        /// <summary>
        /// DeliveryDateTime
        /// </summary>
        public DateTime? DeliveryDateTime { get; set; }

        /// <summary>
        /// Поздравление
        /// </summary>
        public string Congratulation { get; set; }

        /// <summary>
        /// Отправить как подарок
        /// </summary>
        public bool SendAsGift { get; set; }

        /// <summary>
        /// Наименование получателя подарка
        /// </summary>
        public string GiftReceivingName { get; set; }

        /// <summary>
        /// Дата и время создания заказа
        /// </summary>
        public DateTime? CreateOrderDateTime { get; set; }

        /// <summary>
        /// Дата и время отмены заявки заказа
        /// </summary>
        public DateTime? OrderRequestCancelDateTime { get; set; }

        ///// <summary>
        ///// Клиент
        ///// </summary>
        //public ContractorType Customer { get; set; }
        public Guid CustomerId { get; set; }

        /// <summary>
        /// Статус заказа
        /// </summary>
        public OrderStatus OrderStatus { get; set; }

        /// <summary>
        /// Payment type
        /// </summary>
        public PaymentType PaymentType { get; set; }

        /// <summary>
        /// Selected envelope
        /// </summary>
        public EnvelopeType SelectedEnvelope { get; set; }


        public List<CreateCustomerOrderItemModel> OrderItems { get; set; }
    }
}