// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.CustomerOrders.Models
{

    public partial class UpdateCustomerOrderModel
    {
        /// <summary>
        /// Id
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Request datetime
        /// </summary>
        public DateTime OrderRequestDateTime { get; set; }

        /// <summary>
        /// Full delivery address
        /// </summary>
        public string FullDeliveryAddress { get; set; }

        /// <summary>
        /// Deliverable
        /// </summary>
        public bool Deliverable { get; set; }

        /// <summary>
        /// AdditionalInformation
        /// </summary>
        public string AdditionalInformation { get; set; }

        /// <summary>
        /// Поздравление
        /// </summary>
        public string Congratulation { get; set; }
    }
}