// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.ProductCategories.Models
{
    /// <summary>
    /// Модель просмотра родительской категория
    /// </summary>
    public partial class ParentCategoryModel
    {
        /// <summary>
        /// Уникальный идентификатор (primary key)
        /// </summary>
        public Guid? Id { get; set; }

        /// <summary>
        /// Название категории 
        /// </summary>
        public string Name { get; set; }
    }
}