// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.Favorits.Models
{

    public partial class CreateFavoriteModel
    {
        /// <summary>
        /// Customer
        /// </summary>
        public Guid CustomerId { get; set; }

        /// <summary>
        /// Product
        /// </summary>
        public Guid ProductId { get; set; }
    }
}