// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.Contents.Models
{

    public partial class SliderModel
    {
        /// <summary>
        /// Уникальный идентификатор (primary key)
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Id файла
        /// </summary>
        public Guid FileId { get; set; }

        /// <summary>
        /// File
        /// </summary>
        public FileModel File { get; set; }

        /// <summary>
        /// Позиция
        /// </summary>
        public int OrderIndex { get; set; }

        /// <summary>
        /// Link
        /// </summary>
        public string Url { get; set; }

        /// <summary>
        /// Is public
        /// </summary>
        public bool IsPublic { get; set; }

        /// <summary>
        /// Image url
        /// </summary>
        public string ImageUrl { get; set; }
    }
}