// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.Products.Models;
using System;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products
{
    /// <summary>
    /// Прокси для GetAvailableProductsShortInfoByIdsQuery
    /// </summary>
    public partial class GetAvailableProductsShortInfoByIdsQueryProxy : ProxyBase<List<Guid>, IEnumerable<ProductShortInfoModel>>
    {
        public GetAvailableProductsShortInfoByIdsQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}