// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.Products.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products
{
    /// <summary>
    /// Прокси для GetCustomerFavoritProductsShortInfoQuery
    /// </summary>
    public partial class GetCustomerFavoritProductsShortInfoQueryProxy : ProxyBaseNoInput<IEnumerable<ProductShortInfoModel>>
    {
        public GetCustomerFavoritProductsShortInfoQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}