// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.Products.Models;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products
{
    /// <summary>
    /// Прокси для GetProductByProductSeoLinkQuery
    /// </summary>
    public partial class GetProductByProductSeoLinkQueryProxy : ProxyBase<string, ProductModel>
    {
        public GetProductByProductSeoLinkQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}