// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.Products.Models;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products
{
    /// <summary>
    /// Прокси для GetProductsPageShortInfoBySeoLinkQuery
    /// </summary>
    public partial class GetProductsPageShortInfoBySeoLinkQueryProxy : ProxyBase<GetProductsPagingModel, ProductPageShortInfoModel>
    {
        public GetProductsPageShortInfoBySeoLinkQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}