// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.Products.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products
{
    /// <summary>
    /// Прокси для GetProductsShortInfoByProductTagSeoQuery
    /// </summary>
    public partial class GetProductsShortInfoByProductTagSeoQueryProxy : ProxyBase<List<string>, IEnumerable<ProductShortInfoModel>>
    {
        public GetProductsShortInfoByProductTagSeoQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}