// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.Products.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products
{
    /// <summary>
    /// Прокси для GetProductTagsQuery
    /// </summary>
    public partial class GetProductTagsQueryProxy : ProxyBaseNoInput<IEnumerable<ProductTagModel>>
    {
        public GetProductTagsQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}