// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.Products.Models;
using System;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products
{
    /// <summary>
    /// Прокси для GetProductOffersQuery
    /// </summary>
    public partial class GetProductOffersQueryProxy : ProxyBase<Guid, IEnumerable<OfferModel>>
    {
        public GetProductOffersQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}