// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.Products.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products
{
    /// <summary>
    /// Прокси для GetProductsShortInfoByCategorySeoQuery
    /// </summary>
    public partial class GetProductsShortInfoByCategorySeoQueryProxy : ProxyBase<string, IEnumerable<ProductShortInfoModel>>
    {
        public GetProductsShortInfoByCategorySeoQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}