// AUTOGENERATED!!!!!!!!!!!!

namespace NverCard.Public.Client.ServiceProxies.Commands.IndividualCustomers.Models
{
    /// <summary>
    /// Модель бизнес клиента
    /// </summary>
    public partial class CreateIndividualCustomerModel
    {
        /// <summary>
        /// Логин  
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// Удален? 
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Заблокирован? 
        /// </summary>
        public bool IsBlocked { get; set; }

        /// <summary>
        /// Описание 
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Баланс 
        /// </summary>
        public double? Balance { get; set; }
    }
}