// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.IndividualCustomers.Models
{

    public partial class IndividualCustomerModel
    {

        public Guid Id { get; set; }
    }
}