// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.IndividualCustomers.Models
{
    /// <summary>
    /// Модель редактирования бизнес клиента
    /// </summary>
    public partial class UpdateIndividualCustomerModel
    {
        /// <summary>
        /// Id
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Օգտատիրոջ անվանումը
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Օգտատիրոջ մուտքանունը
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// Բացասական հաշվեկշիռ
        /// </summary>
        public bool NegativeBalanceAllowed { get; set; }

        /// <summary>
        /// Նկարագիր
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Հաշվեկշիռ
        /// </summary>
        public double? Balance { get; set; }

        /// <summary>
        /// Հաշվեկշիռ
        /// </summary>
        public Guid AuthTokenId { get; set; }

        /// <summary>
        /// Գործընկեր
        /// </summary>
        public Guid ContractorId { get; set; }
    }
}