// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts.Models;

namespace NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts
{
    /// <summary>
    /// Прокси для CreateShoppingCartItemCommand
    /// </summary>
    public partial class CreateShoppingCartItemCommandProxy : ProxyBase<CreateShoppingCartItemModel, CreateShoppingCartItemResultModel>
    {
        public CreateShoppingCartItemCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}