// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts.Models;

namespace NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts
{
    /// <summary>
    /// Прокси для CreateShoppingCartItemsForCustomerCommand
    /// </summary>
    public partial class CreateShoppingCartItemsForCustomerCommandProxy : ProxyBaseNoResult<CreateShoppingCartModel>
    {
        public CreateShoppingCartItemsForCustomerCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}