// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts.Models;
using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts
{
    /// <summary>
    /// Прокси для CreateShoppingCartForCustomerCommand
    /// </summary>
    public partial class CreateShoppingCartForCustomerCommandProxy : ProxyBase<Guid, ShoppingCartModel>
    {
        public CreateShoppingCartForCustomerCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}