// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts.Models;

namespace NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts
{
    /// <summary>
    /// Прокси для CreateShoppingCartCommand
    /// </summary>
    public partial class CreateShoppingCartCommandProxy : ProxyBaseNoInput<ShoppingCartModel>
    {
        public CreateShoppingCartCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}