// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts.Models;

namespace NverCard.Public.Client.ServiceProxies.Commands.ShoppingCarts
{
    /// <summary>
    /// Прокси для UpdateShoppingCartItemCommand
    /// </summary>
    public partial class UpdateShoppingCartItemCommandProxy : ProxyBaseNoResult<UpdateShoppingCartItemModel>
    {
        public UpdateShoppingCartItemCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}