// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.IndividualCustomers.Models
{
    /// <summary>
    /// Модель просмотра бизнес клиента
    /// </summary>
    public partial class IndividualCustomerModel
    {
        /// <summary>
        /// Id бизнес клиента
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Id контрактора
        /// </summary>
        public Guid? ContractorId { get; set; }

        /// <summary>
        /// Наименование контрагента
        /// </summary>
        public string ContractorName { get; set; }

        /// <summary>
        /// Наименование
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Գաղտնաբառ
        /// </summary>
        public string PasswordHash { get; set; }

        /// <summary>
        /// Токен авторизации
        /// </summary>
        public Guid AuthTokenId { get; set; }

        /// <summary>
        /// Баланс
        /// </summary>
        public double? Balance { get; set; }

        /// <summary>
        /// Логин
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// Разрешен негативный баланс
        /// </summary>
        public bool NegativeBalanceAllowed { get; set; }

        /// <summary>
        /// Удален? 
        /// </summary>
        public bool IsDeleted { get; set; }

        /// <summary>
        /// Описанние
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Заблокирован? 
        /// </summary>
        public bool IsBlocked { get; set; }
    }
}