// AUTOGENERATED!!!!!!!!!!!!

using System;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.ProductTags.Models
{

    public partial class ProductTagModel
    {

        public Guid Id { get; set; }


        public string Name { get; set; }


        public string SeoLink { get; set; }


        public IEnumerable<ProductShortViewModel> TagProducts { get; set; }
    }
}