// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.IndividualCustomers.Models;

namespace NverCard.Public.Client.ServiceProxies.Queries.IndividualCustomers
{
    /// <summary>
    /// Прокси для GetCurrentIndividualCustomerQuery
    /// </summary>
    public partial class GetCurrentIndividualCustomerQueryProxy : ProxyBaseNoInput<IndividualCustomerModel>
    {
        public GetCurrentIndividualCustomerQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}