// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.IndividualCustomers.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.IndividualCustomers
{
    /// <summary>
    /// Прокси для GetIndividualCustomersQuery
    /// </summary>
    public partial class GetIndividualCustomersQueryProxy : ProxyBaseNoInput<IEnumerable<IndividualCustomerModel>>
    {
        public GetIndividualCustomersQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}