// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.IndividualCustomers.Models;

namespace NverCard.Public.Client.ServiceProxies.Commands.IndividualCustomers
{
    /// <summary>
    /// Прокси для CreateIndividualCustomerCommand
    /// </summary>
    public partial class CreateIndividualCustomerCommandProxy : ProxyBaseNoResult<CreateIndividualCustomerModel>
    {
        public CreateIndividualCustomerCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}