// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.IndividualCustomers.Models;

namespace NverCard.Public.Client.ServiceProxies.Commands.IndividualCustomers
{
    /// <summary>
    /// Прокси для CreateAnonymCustomerCommand
    /// </summary>
    public partial class CreateAnonymCustomerCommandProxy : ProxyBaseNoResult<CreateIndividualCustomerModel>
    {
        public CreateAnonymCustomerCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}