// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.IndividualCustomers.Models;

namespace NverCard.Public.Client.ServiceProxies.Commands.IndividualCustomers
{
    /// <summary>
    /// Прокси для UpdateIndividualCustomerCommand
    /// </summary>
    public partial class UpdateIndividualCustomerCommandProxy : ProxyBaseNoResult<UpdateIndividualCustomerModel>
    {
        public UpdateIndividualCustomerCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}