// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.Favorits.Models
{

    public partial class FavoritModel
    {

        public Guid ProductId { get; set; }
    }
}