// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.CustomerOrders.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.CustomerOrders
{
    /// <summary>
    /// Прокси для GetCustomerOrdersQuery
    /// </summary>
    public partial class GetCustomerOrdersQueryProxy : ProxyBaseNoInput<IEnumerable<CustomerOrderModel>>
    {
        public GetCustomerOrdersQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}