// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.Contents.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.Contents
{
    /// <summary>
    /// Прокси для GetSlidersQuery
    /// </summary>
    public partial class GetSlidersQueryProxy : ProxyBaseNoInput<IEnumerable<SliderModel>>
    {
        public GetSlidersQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}