// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products.Models
{

    public partial class CategorySeoLinkModel
    {
        /// <summary>
        /// ID category
        /// </summary>
        public Guid CategoryId { get; set; }

        /// <summary>
        /// Category name
        /// </summary>
        public string CategoryName { get; set; }

        /// <summary>
        /// Category seo link
        /// </summary>
        public string SeoLink { get; set; }
    }
}