// AUTOGENERATED!!!!!!!!!!!!

namespace NverCard.Public.Client.ServiceProxies.Queries.Products.Models
{

    public partial class GetProductsPagingModel
    {

        public string SeoLink { get; set; }


        public int? MinPrice { get; set; }


        public int? MaxPrice { get; set; }


        public int Skip { get; set; }


        public int Take { get; set; }
    }
}