// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Dictionaries;
using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products.Models
{
    /// <summary>
    /// Модель торгового предложения продукта
    /// </summary>
    public partial class OfferModel
    {
        /// <summary>
        /// Уникальный идентификатор (primary key)
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Значение номинала 
        /// </summary>
        public int Nominal { get; set; }

        /// <summary>
        /// Цена 
        /// </summary>
        public int Price { get; set; }

        /// <summary>
        /// Nominal name
        /// </summary>
        public string NominalName { get; set; }

        /// <summary>
        /// Giftcard type
        /// </summary>
        public GiftCardType GiftCardType { get; set; }
    }
}