// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Dictionaries;
using System;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products.Models
{
    /// <summary>
    /// Модель просмотра продуктов
    /// </summary>
    public partial class ProductModel
    {
        /// <summary>
        /// Id
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Название
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Ссылка на логотип 
        /// </summary>
        public string Picture { get; set; }

        /// <summary>
        /// Доступен
        /// </summary>
        public bool Available { get; set; }

        /// <summary>
        /// Автогенерируемый
        /// </summary>
        public bool IsAutogenerated { get; set; }

        /// <summary>
        /// Гарантированный срок действия
        /// </summary>
        public int? GuaranteedValidityPeriod { get; set; }

        /// <summary>
        /// Длина номера сертификата
        /// </summary>
        public int? CertificateNumberLength { get; set; }

        /// <summary>
        /// Количество символов после отсечения 
        /// </summary>
        public int? AmountOfCharactersAfterClipping { get; set; }

        /// <summary>
        /// Количество отсекаемых с начала символов 
        /// </summary>
        public int? AmountOfCharactersToCutOff { get; set; }

        /// <summary>
        /// Краткое описание
        /// </summary>
        public string ShortDescription { get; set; }

        /// <summary>
        /// описание
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Описание правил использования 
        /// </summary>
        public string DescriptionOfTermsOfUse { get; set; }

        /// <summary>
        /// Ограничения (основные)
        /// </summary>
        public string Restrictions { get; set; }

        /// <summary>
        /// Название номинала
        /// </summary>
        public string NominalName { get; set; }

        /// <summary>
        /// SEO link
        /// </summary>
        public string ProductSeoLink { get; set; }

        /// <summary>
        /// Логотип   
        /// </summary>
        public FileModel Logo { get; set; }

        /// <summary>
        /// Logo model
        /// </summary>
        public ProductImageModel ProductImage { get; set; }

        /// <summary>
        /// Денежное обращение 
        /// </summary>
        public Currency Currency { get; set; }


        public string CurrencyName { get; set; }

        /// <summary>
        /// Тип штрих кода
        /// </summary>
        public BarCodeType BareCodeType { get; set; }

        /// <summary>
        /// product categories
        /// </summary>
        public List<Guid> ProductCategories { get; set; }

        /// <summary>
        /// Collection categories and seolinks
        /// </summary>
        public List<CategorySeoLinkModel> CategoriesSeoLinks { get; set; }

        /// <summary>
        /// Offers
        /// </summary>
        public List<OfferModel> Offers { get; set; }
    }
}