// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Dictionaries;
using System;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products.Models
{

    public partial class ProductShortInfoModel
    {
        /// <summary>
        /// Id
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Название
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// product seo link
        /// </summary>
        public string ProductSeoLink { get; set; }

        /// <summary>
        /// Денежное обращение 
        /// </summary>
        public Currency Currency { get; set; }

        /// <summary>
        /// Currency name
        /// </summary>
        public string CurrencyName { get; set; }

        /// <summary>
        /// Currency value
        /// </summary>
        public string CurrencyValue { get; set; }

        /// <summary>
        /// Название номинала
        /// </summary>
        public string NominalName { get; set; }

        /// <summary>
        /// Tag or category name
        /// </summary>
        public string TagCategoryName { get; set; }

        /// <summary>
        /// Logo model
        /// </summary>
        public ProductImageModel ProductImage { get; set; }

        /// <summary>
        /// Offers
        /// </summary>
        public List<OfferModel> Offers { get; set; }

        /// <summary>
        /// Tags
        /// </summary>
        public List<ProductTagModel> ProductTags { get; set; }

        /// <summary>
        /// Categories
        /// </summary>
        public List<CategorySeoLinkModel> Categories { get; set; }
    }
}