// AUTOGENERATED!!!!!!!!!!!!

using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products.Models
{

    public partial class ProductPageShortInfoModel
    {

        public int AllCount { get; set; }


        public int MinPriceValue { get; set; }


        public int MaxPriceValue { get; set; }


        public IEnumerable<ProductShortInfoModel> Products { get; set; }
    }
}