// AUTOGENERATED!!!!!!!!!!!!

using System;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products.Models
{

    public partial class ProductTagModel
    {
        /// <summary>
        /// Id
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Seo link
        /// </summary>
        public string SeoLink { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Products model
        /// </summary>
        public IEnumerable<ProductShortViewModel> TagProducts { get; set; }
    }
}