// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.Products.Models
{

    public partial class ProductShortViewModel
    {
        /// <summary>
        /// Id
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// product seo link
        /// </summary>
        public string ProductSeoLink { get; set; }

        /// <summary>
        /// Logo model
        /// </summary>
        public ProductImageModel ProductImage { get; set; }
    }
}