// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Dictionaries;
using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.CustomerOrders.Models
{

    public partial class CustomerOrderModel
    {
        /// <summary>
        /// Уникальный идентификатор (primary key)
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Номер заказа
        /// </summary>
        public string Number { get; set; }

        /// <summary>
        /// Статус заказа
        /// </summary>
        public OrderStatus Status { get; set; }

        /// <summary>
        /// Attribute name for orderstatus
        /// </summary>
        public string OrderStatusName { get; set; }

        /// <summary>
        /// Дата и время поступления заявки заказа
        /// </summary>
        public DateTime OrderRequestDateTime { get; set; }

        /// <summary>
        /// Дата и время создания заказа
        /// </summary>
        public DateTime? CreateOrderDateTime { get; set; }

        /// <summary>
        /// Дата и время сборки 
        /// </summary>
        public DateTime? AssemblyDateTime { get; set; }

        /// <summary>
        /// Дата и время отправки 
        /// </summary>
        public DateTime? SendingDateTime { get; set; }

        /// <summary>
        /// Дополнительная информация
        /// </summary>
        public string AdditionalInformation { get; set; }

        /// <summary>
        /// Емаил
        /// </summary>
        public string Email { get; set; }

        /// <summary>
        /// Номер телефона
        /// </summary>
        public string PhoneNumber { get; set; }

        /// <summary>
        /// С доставкой
        /// </summary>
        public bool Deliverable { get; set; }

        /// <summary>
        /// С доставкой
        /// </summary>
        public string FullDeliveryAddress { get; set; }

        /// <summary>
        /// Дата доставки
        /// </summary>
        public DateTime? DeliveryDateTime { get; set; }

        /// <summary>
        /// Тип контрагента
        /// </summary>
        public Guid CustomerId { get; set; }

        /// <summary>
        /// Автоматизированный клиент
        /// </summary>
        public string CustomerName { get; set; }

        /// <summary>
        /// Поздравление
        /// </summary>
        public string Congratulation { get; set; }

        /// <summary>
        /// Total price
        /// </summary>
        public int TotalPrice { get; set; }

        /// <summary>
        /// Total cards count
        /// </summary>
        public int CertificatesCount { get; set; }
    }
}