// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.ProductToProductTagLinks.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.ProductToProductTagLinks
{
    /// <summary>
    /// Прокси для GetProductToProductTagLinksSelectQuery
    /// </summary>
    public partial class GetProductToProductTagLinksSelectQueryProxy : ProxyBaseNoInput<IEnumerable<ProductTagToProductLinkModel>>
    {
        public GetProductToProductTagLinksSelectQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}