// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.CustomerOrderItems.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Commands.CustomerOrderItems
{
    /// <summary>
    /// Прокси для CreateCustomerOrderItemCommand
    /// </summary>
    public partial class CreateCustomerOrderItemCommandProxy : ProxyBaseNoResult<IEnumerable<CreateCustomerOrderItemInputModel>>
    {
        public CreateCustomerOrderItemCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}