// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.CustomerOrderItems.Models
{

    public partial class CreateCustomerOrderItemInputModel
    {
        /// <summary>
        /// Количество
        /// </summary>
        public int Quantity { get; set; }

        /// <summary>
        /// Id торгового предложения для бизнес клиента
        /// </summary>
        public Guid OfferId { get; set; }

        /// <summary>
        /// Customer order
        /// </summary>
        public Guid CustomerOrderId { get; set; }
    }
}