// AUTOGENERATED!!!!!!!!!!!!

namespace NverCard.Public.Client.ServiceProxies.Commands.Authenticators.Models
{

    public partial class AuthenticateIndividualCustomerRequestModel
    {

        public string PhoneNumber { get; set; }


        public string ConfirmCode { get; set; }
    }
}