// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.Authenticators.Models
{

    public partial class AuthenticateIndividualCustomerResultModel
    {

        public Guid Id { get; set; }


        public string UserName { get; set; }


        public string Name { get; set; }


        public string AccessToken { get; set; }
    }
}