// AUTOGENERATED!!!!!!!!!!!!

namespace NverCard.Public.Client.ServiceProxies.Commands.Authenticators.Models
{

    public partial class CreateAuthenticatorModel
    {
        /// <summary>
        /// Phone number
        /// </summary>
        public string PhoneNumber { get; set; }
    }
}