// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Dictionaries;
using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.ShoppingCarts.Models
{

    public partial class ShoppingCartItemModel
    {

        public Guid Id { get; set; }


        public int Quantity { get; set; }


        public Guid ShoppingCartId { get; set; }


        public Guid OfferId { get; set; }


        public string ProductName { get; set; }


        public int Nominal { get; set; }


        public string NominalName { get; set; }


        public int Price { get; set; }


        public GiftCardType GiftcardType { get; set; }


        public string ImageUrl { get; set; }


        public string ProductSeoLink { get; set; }
    }
}