// AUTOGENERATED!!!!!!!!!!!!

using System;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.ShoppingCarts.Models
{

    public partial class ShoppingCartModel
    {

        public Guid Id { get; set; }

        /// <summary>
        /// Creation date time
        /// </summary>
        public DateTime CreationDateTime { get; set; }

        /// <summary>
        /// Assembly date time
        /// </summary>
        public DateTime? AssemblyDateTime { get; set; }


        public Guid CustomerId { get; set; }

        /// <summary>
        /// Shopping cart items
        /// </summary>
        public ICollection<ShoppingCartItemModel> CartItems { get; set; }
    }
}