// AUTOGENERATED!!!!!!!!!!!!

namespace NverCard.Public.Client.ServiceProxies.Queries.ProductTags
{
    /// <summary>
    /// Прокси для GetProductTagNameBySeoQuery
    /// </summary>
    public partial class GetProductTagNameBySeoQueryProxy : ProxyBase<string, string>
    {
        public GetProductTagNameBySeoQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}