// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.ProductTags.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.ProductTags
{
    /// <summary>
    /// Прокси для GetProductTagsSelectQuery
    /// </summary>
    public partial class GetProductTagsSelectQueryProxy : ProxyBaseNoInput<IEnumerable<ProductTagModel>>
    {
        public GetProductTagsSelectQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}