// AUTOGENERATED!!!!!!!!!!!!

namespace NverCard.Public.Client.ServiceProxies.Queries.GiftCertificates.Models
{

    public partial class CertificateInputModel
    {
        /// <summary>
        /// Only active
        /// </summary>
        public bool OnlyActive { get; set; }

        /// <summary>
        /// Months count
        /// </summary>
        public int? Months { get; set; }
    }
}