// AUTOGENERATED!!!!!!!!!!!!

namespace NverCard.Public.Client.ServiceProxies.Queries.GiftCertificates.Models
{

    public partial class CertificatePdfModel
    {
        /// <summary>
        /// file name
        /// </summary>
        public string FileName { get; set; }

        /// <summary>
        /// file data
        /// </summary>
        public byte[] Data { get; set; }
    }
}