// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Queries.GiftCertificates.Models
{

    public partial class CertificateModel
    {
        /// <summary>
        /// Id
        /// </summary>
        public Guid Id { get; set; }

        /// <summary>
        /// Product name
        /// </summary>
        public string ProductName { get; set; }

        /// <summary>
        /// expiration date
        /// </summary>
        public DateTime? ExpirationDate { get; set; }

        /// <summary>
        /// Nominal
        /// </summary>
        public int Nominal { get; set; }

        /// <summary>
        /// image url
        /// </summary>
        public string ImageUrl { get; set; }

        /// <summary>
        /// Seo link for product
        /// </summary>
        public string ProductSeoLink { get; set; }
    }
}