// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Queries.Favorits.Models;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Queries.Favorits
{
    /// <summary>
    /// Прокси для GetCustomerFavoritsQuery
    /// </summary>
    public partial class GetCustomerFavoritsQueryProxy : ProxyBaseNoInput<IEnumerable<FavoritModel>>
    {
        public GetCustomerFavoritsQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}