// AUTOGENERATED!!!!!!!!!!!!

namespace NverCard.Public.Client.ServiceProxies.Queries.Favorits
{
    /// <summary>
    /// Прокси для GetCustomerFavoritsCountQuery
    /// </summary>
    public partial class GetCustomerFavoritsCountQueryProxy : ProxyBaseNoInput<int>
    {
        public GetCustomerFavoritsCountQueryProxy(Executor executor) : base(executor)
        {
        }
    }
}