// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.Favorits
{
    /// <summary>
    /// Прокси для CreateFavoriteCommand
    /// </summary>
    public partial class CreateFavoriteCommandProxy : ProxyBase<Guid, Guid?>
    {
        public CreateFavoriteCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}