// AUTOGENERATED!!!!!!!!!!!!

using System;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Commands.Favorits
{
    /// <summary>
    /// Прокси для CreateOrRemoveFavoriteCommand
    /// </summary>
    public partial class CreateOrRemoveFavoriteCommandProxy : ProxyBaseNoResult<List<Guid>>
    {
        public CreateOrRemoveFavoriteCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}