// AUTOGENERATED!!!!!!!!!!!!

using System;
using System.Collections.Generic;

namespace NverCard.Public.Client.ServiceProxies.Commands.Favorits
{
    /// <summary>
    /// Прокси для CreateFavoritesCommand
    /// </summary>
    public partial class CreateFavoritesCommandProxy : ProxyBaseNoResult<List<Guid>>
    {
        public CreateFavoritesCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}