// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.Favorits.Models;

namespace NverCard.Public.Client.ServiceProxies.Commands.Favorits
{
    /// <summary>
    /// Прокси для CreateFavoriteForCustomerCommand
    /// </summary>
    public partial class CreateFavoriteForCustomerCommandProxy : ProxyBaseNoResult<CreateFavoriteModel>
    {
        public CreateFavoriteForCustomerCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}