// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.Favorits
{
    /// <summary>
    /// Прокси для RemoveFavoriteByProductIdCommand
    /// </summary>
    public partial class RemoveFavoriteByProductIdCommandProxy : ProxyBaseNoResult<Guid>
    {
        public RemoveFavoriteByProductIdCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}