// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.Favorits
{
    /// <summary>
    /// Прокси для RemoveShoppingCartItemCommand
    /// </summary>
    public partial class RemoveShoppingCartItemCommandProxy : ProxyBaseNoResult<Guid>
    {
        public RemoveShoppingCartItemCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}