// AUTOGENERATED!!!!!!!!!!!!

using System;

namespace NverCard.Public.Client.ServiceProxies.Commands.Favorits
{
    /// <summary>
    /// Прокси для RemoveFavoriteCommand
    /// </summary>
    public partial class RemoveFavoriteCommandProxy : ProxyBaseNoResult<Guid>
    {
        public RemoveFavoriteCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}