// AUTOGENERATED!!!!!!!!!!!!

namespace NverCard.Public.Client.ServiceProxies.Commands.Authenticators
{
    /// <summary>
    /// Прокси для CheckIsTokenConfirmationAvailableCommand
    /// </summary>
    public partial class CheckIsTokenConfirmationAvailableCommandProxy : ProxyBase<string, int>
    {
        public CheckIsTokenConfirmationAvailableCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}