// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.Authenticators.Models;

namespace NverCard.Public.Client.ServiceProxies.Commands.Authenticators
{
    /// <summary>
    /// Прокси для CheckValidConfirmTokenCommand
    /// </summary>
    public partial class CheckValidConfirmTokenCommandProxy : ProxyBase<AuthenticateIndividualCustomerRequestModel, AuthenticateIndividualCustomerResultModel>
    {
        public CheckValidConfirmTokenCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}