// AUTOGENERATED!!!!!!!!!!!!

using NverCard.Public.Client.ServiceProxies.Commands.Authenticators.Models;

namespace NverCard.Public.Client.ServiceProxies.Commands.Authenticators
{
    /// <summary>
    /// Прокси для CreateAuthenticatorCommand
    /// </summary>
    public partial class CreateAuthenticatorCommandProxy : ProxyBaseNoResult<CreateAuthenticatorModel>
    {
        public CreateAuthenticatorCommandProxy(Executor executor) : base(executor)
        {
        }
    }
}